Project/urls.py
from django.conf.urls import include,url
from django.contrib import admin
#from dashing.utils import router


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^weather/', include('weather.urls'))]

weather/urls.py
from django.conf.urls import url
from . import views

app_name = 'weather'
#including all html pages
#in url patterns the url() function matches the regular expression(r) after ^ and then takes it to the function in views.py whose name is specified in name
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pid1>[0-9]+)/$', views.pindex, name='detail'),
    url(r'^graph/', views.graph, name='graph'),
    url(r'^login/', views.login_user,name='login_user'),
    url(r'^register/', views.register,name='register'),
    url(r'^maps/', views.maps, name='maps'),
    url(r'^logout/', views.logout_user, name='logout'),
    url(r'^plants/', views.plants, name='plants'),
    url(r'^addplants/', views.addplants, name='addplants'),
    url(r'^removeplants/', views.removeplants, name='removeplants'),
    url(r'^motor/', views.motor, name='motor'),
    url(r'^index1/', views.index1, name='index1'),
    url(r'^findtime/', views.find_time, name='find_time'),
    url(r'^getplants/', views.getplants, name='getplants'),    
]

weather/models.py
from django.db import models
from datetime import time
import datetime
import time

#creating table for sensor readings
class plant(models.Model):
    pid1 = models.IntegerField(primary_key=True)
    latitude = models.FloatField(default=0)
    longitude = models.FloatField(default=0)
    def __str__(self):
        return str(self.pid1)

#different fields are created for the class sensorreadings
class sensorreadings(models.Model):
    pid = models.ForeignKey(plant,null=True,on_delete=models.CASCADE)
    temp = models.CharField(max_length=30)
    humd = models.CharField(max_length=50)
    moi = models.CharField(max_length=50)
    date = models.CharField(max_length=150)
    detect = models.CharField(max_length=20)
    rain = models.CharField(max_length=30)
    ph = models.CharField(max_length=30)
    def __str__(self):
        return self.temp

class common(models.Model):
    turb = models.CharField(max_length=30)
    level = models.CharField(max_length=30)
    def __str__(self):
        return self.turb

weather/forms.py
from django.contrib.auth.models import User
from django import forms

#forms are created to add new users , add plants and also to remove plants

#the following class adds new user form and also creates approp0riate fields
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
     model = User
     fields = ['username','email','password']

#the following class add new plants
class plantForm(forms.Form):
    pid1 = forms.CharField(max_length=100)
    latitude = forms.CharField(max_length=100)
    longitude = forms.CharField(max_length=100)

#the following class deletes the plant
class deleteForm(forms.Form):
    pid1 = forms.CharField(max_length=100)

weather/views.py
#sending data

from django.views.decorators.csrf import csrf_exempt # command for csrf exemption
import json
from django.http import JsonResponse,HttpResponseRedirect,HttpResponse

from .models import *
from django.core import serializers
#login
from django.shortcuts import render
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from .forms import UserForm,plantForm,deleteForm


#sending data
data = []
data1 = []
@csrf_exempt #CROSS SITE REQUEST FORGERY
def index(request): #A FUNCTION TO RECIEVE REQUESTS IS CALLED WHEN WEATHER URL IS CALLED
    if request.method == 'POST':
        data.append(json.loads(json.dumps({"temperature": json.loads((request.body).decode('utf-8')).get('temperature'), "humidity": json.loads((request.body).decode('utf-8')).get('humidity'),"moisture": json.loads((request.body).decode('utf-8')).get('moisture'), "date": json.loads((request.body).decode('utf-8')).get('date'),"detect": json.loads((request.body).decode('utf-8')).get('detect'),"pid": json.loads((request.body).decode('utf-8')).get('pid'),"ph": json.loads((request.body).decode('utf-8')).get('ph')})))
        p=json.loads((request.body).decode('utf-8')).get('pid')
        #print(json.loads((request.body).decode('utf-8')).get('ph'))
        a = sensorreadings.objects.create(temp=json.loads((request.body).decode('utf-8')).get('temperature'),humd=json.loads((request.body).decode('utf-8')).get('humidity'),moi=json.loads((request.body).decode('utf-8')).get('moisture'),date=json.loads((request.body).decode('utf-8')).get('date'),detect=json.loads((request.body).decode('utf-8')).get('detect'),pid=plant(p),ph=json.loads((request.body).decode('utf-8')).get('ph'))
        a.save() #WE CREATE A OBJECT TO STORE SENSOR READINGS AND THEN WE STORE THOSE READING INTO THE DATABASE
                 #JSON MEANS JAVA SCRIPT OBJECT NOTATION , WE CONVERTING FROM JSON TO DICTIONERY
        return JsonResponse(data,safe=False) #SENDING DATA TO HTML PAGE
    if request.method == 'GET':
        return JsonResponse(json.loads(json.dumps(data)), safe=False) #WHEN THE BROWSER REQUESTS DATA WE SEND JSON RESPONSE

@csrf_exempt
def index1(request):
    if request.method == 'POST':
        data1.append(json.loads(json.dumps({"level" : json.loads((request.body).decode('utf-8')).get('level'), "turb" : json.loads((request.body).decode('utf-8')).get('turb')})))
        #print(json.loads((request.body).decode('utf-8')).get('ph'))
        a = common.objects.create(level=json.loads((request.body).decode('utf-8')).get('level'),turb=json.loads((request.body).decode('utf-8')).get('turb'))
        a.save() #WE CREATE A OBJECT TO STORE SENSOR READINGS AND THEN WE STORE THOSE READING INTO THE DATABASE
        #JSON MEANS JAVA SCRIPT OBJECT NOTATION , WE CONVERTING FROM JSON TO DICTIONERY
        return JsonResponse(data1,safe=False) #SENDING DATA TO HTML PAGE
    if request.method == 'GET':
        return JsonResponse(json.loads(json.dumps(data1)), safe=False)

def plants(request): #A FUNCTION WHICH RETURNS ALL PLANTS WHEN PLANTS/ URL IS CALLED
    all_p=plant.objects.all() # all the stored plant details are retrived
    arr=[] #an empty array
    for p in all_p: #A FOR LOOP
        arr.append(p.pid1)
        print(arr)
    return JsonResponse({'pids':arr},safe=True)


def pindex(request,pid1): #A FUNCTION TO FETCH THE DETAILS OF A PRATICULAR PLANT WE WANT
    all_plants = plant.objects.all() # all the stored plant details are retrived
    html = []
    for plants in all_plants:
        if(str(plants.pid1)) == str(pid1): #CHECKS IF QUERIED PLANT ID AND PLANT ID IN DATABASE IS SAME
            html = {"pid1":plants.pid1,"latitude":plants.latitude,"longitude":plants.longitude} # DICTIONARY
    html1 = list(map(lambda x: x['fields'],json.loads(serializers.serialize('json',sensorreadings.objects.filter(pid=pid1)))))
    return JsonResponse({"loc":html, "values":html1}, safe=False)

@login_required #these @ are known as decorators .Here they help us to view the graph only if we succesfully furnish our login details
def graph(request): #FUNCTION IS CALLED WHEN graph/ url is called
    p = sensorreadings.objects.filter(pid=1)[::-1][0] #returns the latest sensor reading of the desired plant id
    p1 = common.objects.all()[::-1][0]
    # print('temp', p.moi)

    return render(request,"index.html",{'k':p, 'k1':p1}) # data is rendered to index.html in the form of dictionary

@login_required
def maps(request):
    for k in sensorreadings.objects.all():
        print(k.moi)
    return render(request,"maps.html",{'k':k})

#login
@csrf_exempt
def login_user(request):
    if request.method == "POST":#getting user details from the page
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)#check if the user is there in database
        if user is not None:
            if user.is_active:
                login(request, user)#login user and redirect to index page
                flag=1
                #return render(request, 'index.html')
                return HttpResponseRedirect('/weather/graph')
            else:
                return render(request, 'login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'login.html', {'error_message': 'Invalid login'})
    return render(request, 'login.html')

@csrf_exempt
def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                #return render(request,'index.html')
                return HttpResponseRedirect('/weather/graph')
    context = {
        "form": form,
    }
    return render(request, 'register.html')

def logout_user(request):
    logout(request)
    return HttpResponseRedirect('/weather/login')

#function to add plants
@login_required
def addplants(request):
    form = plantForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            pid1 = form.cleaned_data['pid1']
            longitude = form.cleaned_data['longitude']
            latitude = form.cleaned_data['latitude']
            print(pid1)
            print(longitude)
            foo = plant.objects.create(pid1 = int(pid1),latitude = float(latitude), longitude = float(longitude))
            return HttpResponseRedirect('/weather/graph') #we are redirected to home page
        else:
            form = plantForm()
    return render(request,'addplants.html',{'form':form})

#function to remove plants
def removeplants(request):
    form=deleteForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            pid1= form.cleaned_data['pid1']
            p=plant.objects.filter(pid1=pid1)
            p.delete()
            return HttpResponseRedirect('/weather/graph')
        else:
            form = deleteForm()
    return render(request,'removeplants.html',{'form':form})

st = []
@csrf_exempt
def motor(request):
    if request.method == 'POST':
        on = json.loads(request.body.decode('utf-8')).get('on')
        st.append(on)
        return JsonResponse({'success': 'true' }, safe=True)
    if request.method == 'GET':
        return HttpResponse(st[-1])

#functiom to modify plant details
#def modifyplants(request):

@csrf_exempt
def find_time(request):
    return render(request,"index.html")

def viewplants(request):
    p=plant.objects.filter(pid1=1)
    p.delete()
    unique=[1,2,6,8,7,3,9]
    li=unique.sort()
    hell={'un':li}
    return render(request,'removeplants.html',hell)

def getplants(request):
    l=plant.objects.filter(pid1=1)
    l.delete()
    hell={'un':[1,2,3,2,23,2]}
    return render(request,'getplants.html',hell)

def likeplants(request):
    l=plant.objects.all()
    hell={'un':l}
    return render(request,'getplants.html',hell)

weather/templates/addplants.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <link href="{% static 'login.css' %}" rel="stylesheet"><!-- sub-bootstrap and modified style functionalities-->
  <div class="jumbotron">
      <div class="container">
          <form method="POST">
<!--cookies issue-->
    {% csrf_token %}
              <div class="login__row">
                  <input type="text" class="login__input" placeholder="Enter New Plant ID" name="pid1"/>
              </div>
      <div class="login__row">
<!--allows to draw icons-animation-->
        <input type="text" class="login__input" placeholder="Latitude" name="latitude" />
      </div>
      <div class="login__row">
         <input type="text" class="login__input" placeholder="Longitude" name="longitude"/>
      </div>
        <button  class="login__submit" >ADD</button>
</form>
      </div>
  </div>
{% endblock %}

weather/templates/base.html
{% load static %}
<html class="loading">   <!--loads the loading class features-->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>WaterSense</title>
    <!--loading the corresponding css and js files-->
    <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet"><!--accessing bootstrap css functionalities-->
    <link href="{% static 'dashboard.css' %}" rel="stylesheet"><!-- sub-bootstrap and modified style functionalities-->
    <link href="{% static 'svganimate.css' %}" rel="stylesheet"><!--svg icons styling-->
    <script src="{% static 'chart.bundle.js' %}"></script><!--accessing chart.js functionalities-->
    <script src="{% static 'jquery-3.1.1.slim.min.js' %}"></script>
    <script src="{% static 'tether.min.js' %}"></script>
    <script src="{% static 'bootstrap.min.js' %}"></script><!--accessing bootstrap js functionalities-->


    <!--for the loading page,replaces loading class with the normal class,thus gives the loading effect-->
    <script>
        var html = document.getElementsByTagName('html')[0];
        var removeLoading = function() {
        setTimeout(function(){
            html.className = html.className.replace(/loading/, '');
          }, 1000);
         };
        removeLoading();
    </script>

    <style>
    body {
            font-size: 100% !important;
        }

      .circleBase {
        border-radius: 50%;
        width: 50px;
        height: 50px;
        background-image: url("{% static 'profile.png' %}");
        border: 2px solid black;
        background-color: antiquewhite;
      }
        .btn-primary,
        .btn-primary:hover,
        .btn-primary:active,
        .btn-primary:visited,
        .btn-primary:focus {
            background-color: #110D23;
        }


        hr {
          margin-top: 2rem;
          margin-bottom: 2rem;
        }
  </style>
 </head>


  <body>
    <nav class="navbar navbar-toggleable-md  fixed-top " style="background-color:#110D23 ">
      <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#"><svg class="login__icon name svg-icon" viewBox="0 0 20 20">
							<path fill="none" d="M10,16.513c-2.249,0-4.071-1.822-4.071-4.07c0-0.226-0.182-0.407-0.407-0.407c-0.225,0-0.407,0.182-0.407,0.407c0,2.697,2.187,4.885,4.885,4.885c0.225,0,0.407-0.183,0.407-0.407S10.225,16.513,10,16.513M10,1.044c-0.814,0-6.513,6.92-6.513,11.398c0,3.597,2.916,6.513,6.513,6.513c3.597,0,6.513-2.916,6.513-6.513C16.513,7.964,10.813,1.044,10,1.044 M10,18.141c-3.148,0-5.699-2.65-5.699-5.92C4.301,8.372,9.593,2.011,10,2.011c0.407,0,5.698,6.36,5.698,10.209C15.698,15.49,13.147,18.141,10,18.141"></path>
						</svg>WaterSense</a>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
            <a class="nav link" href="#">Hello<br>{{user.username}}</a>
          </li>
            <li class="nav-item">
                <div class="circleBase type2"></div>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'weather:graph' %}"><svg class="login__icon name svgtop-icon" viewBox="0 0 20 20">
<path d="M18.121,9.88l-7.832-7.836c-0.155-0.158-0.428-0.155-0.584,0L1.842,9.913c-0.262,0.263-0.073,0.705,0.292,0.705h2.069v7.042c0,0.227,0.187,0.414,0.414,0.414h3.725c0.228,0,0.414-0.188,0.414-0.414v-3.313h2.483v3.313c0,0.227,0.187,0.414,0.413,0.414h3.726c0.229,0,0.414-0.188,0.414-0.414v-7.042h2.068h0.004C18.331,10.617,18.389,10.146,18.121,9.88 M14.963,17.245h-2.896v-3.313c0-0.229-0.186-0.415-0.414-0.415H8.342c-0.228,0-0.414,0.187-0.414,0.415v3.313H5.032v-6.628h9.931V17.245z M3.133,9.79l6.864-6.868l6.867,6.868H3.133z"></path></svg>Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'weather:maps' %}"><svg class="login__icon name svgtop-icon" viewBox="0 0 20 20">
							<path d="M17.431,2.156h-3.715c-0.228,0-0.413,0.186-0.413,0.413v6.973h-2.89V6.687c0-0.229-0.186-0.413-0.413-0.413H6.285c-0.228,0-0.413,0.184-0.413,0.413v6.388H2.569c-0.227,0-0.413,0.187-0.413,0.413v3.942c0,0.228,0.186,0.413,0.413,0.413h14.862c0.228,0,0.413-0.186,0.413-0.413V2.569C17.844,2.342,17.658,2.156,17.431,2.156 M5.872,17.019h-2.89v-3.117h2.89V17.019zM9.587,17.019h-2.89V7.1h2.89V17.019z M13.303,17.019h-2.89v-6.651h2.89V17.019z M17.019,17.019h-2.891V2.982h2.891V17.019z"></path>
						</svg>Database</a>
          </li>
           <li class="nav-item" align="right">
            <a class="nav-link" href="{% url 'weather:logout' %}"><svg class="login__icon name svgtop-icon" viewBox="0 0 20 20">
							<path fill="none" d="M8.416,3.943l1.12-1.12v9.031c0,0.257,0.208,0.464,0.464,0.464c0.256,0,0.464-0.207,0.464-0.464V2.823l1.12,1.12c0.182,0.182,0.476,0.182,0.656,0c0.182-0.181,0.182-0.475,0-0.656l-1.744-1.745c-0.018-0.081-0.048-0.16-0.112-0.224C10.279,1.214,10.137,1.177,10,1.194c-0.137-0.017-0.279,0.02-0.384,0.125C9.551,1.384,9.518,1.465,9.499,1.548L7.76,3.288c-0.182,0.181-0.182,0.475,0,0.656C7.941,4.125,8.234,4.125,8.416,3.943z M15.569,6.286h-2.32v0.928h2.32c0.512,0,0.928,0.416,0.928,0.928v8.817c0,0.513-0.416,0.929-0.928,0.929H4.432c-0.513,0-0.928-0.416-0.928-0.929V8.142c0-0.513,0.416-0.928,0.928-0.928h2.32V6.286h-2.32c-1.025,0-1.856,0.831-1.856,1.856v8.817c0,1.025,0.832,1.856,1.856,1.856h11.138c1.024,0,1.855-0.831,1.855-1.856V8.142C17.425,7.117,16.594,6.286,15.569,6.286z"></path>
						</svg>Logout <span class="sr-only"></span></a>
          </li>

        </ul>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-sm-2 col-md-2 hidden-xs-down bg-faded sidebar">
          <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'weather:graph' %}"><svg class="login__icon name svgtop-icon" viewBox="0 0 20 20">
							<path fill="none" d="M16.803,18.615h-4.535c-1,0-1.814-0.812-1.814-1.812v-4.535c0-1.002,0.814-1.814,1.814-1.814h4.535c1.001,0,1.813,0.812,1.813,1.814v4.535C18.616,17.803,17.804,18.615,16.803,18.615zM17.71,12.268c0-0.502-0.405-0.906-0.907-0.906h-4.535c-0.501,0-0.906,0.404-0.906,0.906v4.535c0,0.502,0.405,0.906,0.906,0.906h4.535c0.502,0,0.907-0.404,0.907-0.906V12.268z M16.803,9.546h-4.535c-1,0-1.814-0.812-1.814-1.814V3.198c0-1.002,0.814-1.814,1.814-1.814h4.535c1.001,0,1.813,0.812,1.813,1.814v4.534C18.616,8.734,17.804,9.546,16.803,9.546zM17.71,3.198c0-0.501-0.405-0.907-0.907-0.907h-4.535c-0.501,0-0.906,0.406-0.906,0.907v4.534c0,0.501,0.405,0.908,0.906,0.908h4.535c0.502,0,0.907-0.406,0.907-0.908V3.198z M7.733,18.615H3.198c-1.002,0-1.814-0.812-1.814-1.812v-4.535c0-1.002,0.812-1.814,1.814-1.814h4.535c1.002,0,1.814,0.812,1.814,1.814v4.535C9.547,17.803,8.735,18.615,7.733,18.615zM8.64,12.268c0-0.502-0.406-0.906-0.907-0.906H3.198c-0.501,0-0.907,0.404-0.907,0.906v4.535c0,0.502,0.406,0.906,0.907,0.906h4.535c0.501,0,0.907-0.404,0.907-0.906V12.268z M7.733,9.546H3.198c-1.002,0-1.814-0.812-1.814-1.814V3.198c0-1.002,0.812-1.814,1.814-1.814h4.535c1.002,0,1.814,0.812,1.814,1.814v4.534C9.547,8.734,8.735,9.546,7.733,9.546z M8.64,3.198c0-0.501-0.406-0.907-0.907-0.907H3.198c-0.501,0-0.907,0.406-0.907,0.907v4.534c0,0.501,0.406,0.908,0.907,0.908h4.535c0.501,0,0.907-0.406,0.907-0.908V3.198z"></path>
						</svg>Readings <span class="sr-only">(current)</span></a>
            </li>
              <li class="nav-item">
            <a class="nav-link" href="{% url 'weather:maps' %}"><svg class="login__icon name svgtop-icon" viewBox="0 0 20 20">
							<path d="M17.431,2.156h-3.715c-0.228,0-0.413,0.186-0.413,0.413v6.973h-2.89V6.687c0-0.229-0.186-0.413-0.413-0.413H6.285c-0.228,0-0.413,0.184-0.413,0.413v6.388H2.569c-0.227,0-0.413,0.187-0.413,0.413v3.942c0,0.228,0.186,0.413,0.413,0.413h14.862c0.228,0,0.413-0.186,0.413-0.413V2.569C17.844,2.342,17.658,2.156,17.431,2.156 M5.872,17.019h-2.89v-3.117h2.89V17.019zM9.587,17.019h-2.89V7.1h2.89V17.019z M13.303,17.019h-2.89v-6.651h2.89V17.019z M17.019,17.019h-2.891V2.982h2.891V17.019z"></path>
						</svg>Database</a>
          </li>
            <li class="nav-item">
              <a class="nav-link" href="#"><svg class="login__icon name svgtop-icon" viewBox="0 0 20 20">
							<path  d="M9.896,3.838L0.792,1.562v14.794l9.104,2.276L19,16.356V1.562L9.896,3.838z M9.327,17.332L1.93,15.219V3.27
								l7.397,1.585V17.332z M17.862,15.219l-7.397,2.113V4.855l7.397-1.585V15.219z"></path>
						</svg>About Us</a>
            </li>
           <li class="nav-item">
              <a class="nav-link" href="#" onclick="speakDate()"><svg class="login__icon name svgtop-icon" viewBox="0 0 20 20" >
							<path  d="M11.088,2.542c0.063-0.146,0.103-0.306,0.103-0.476c0-0.657-0.534-1.19-1.19-1.19c-0.657,0-1.19,0.533-1.19,1.19c0,0.17,0.038,0.33,0.102,0.476c-4.085,0.535-7.243,4.021-7.243,8.252c0,4.601,3.73,8.332,8.332,8.332c4.601,0,8.331-3.73,8.331-8.332C18.331,6.562,15.173,3.076,11.088,2.542z M10,1.669c0.219,0,0.396,0.177,0.396,0.396S10.219,2.462,10,2.462c-0.22,0-0.397-0.177-0.397-0.396S9.78,1.669,10,1.669z M10,18.332c-4.163,0-7.538-3.375-7.538-7.539c0-4.163,3.375-7.538,7.538-7.538c4.162,0,7.538,3.375,7.538,7.538C17.538,14.957,14.162,18.332,10,18.332z M10.386,9.26c0.002-0.018,0.011-0.034,0.011-0.053V5.24c0-0.219-0.177-0.396-0.396-0.396c-0.22,0-0.397,0.177-0.397,0.396v3.967c0,0.019,0.008,0.035,0.011,0.053c-0.689,0.173-1.201,0.792-1.201,1.534c0,0.324,0.098,0.625,0.264,0.875c-0.079,0.014-0.155,0.043-0.216,0.104l-2.244,2.244c-0.155,0.154-0.155,0.406,0,0.561s0.406,0.154,0.561,0l2.244-2.242c0.061-0.062,0.091-0.139,0.104-0.217c0.251,0.166,0.551,0.264,0.875,0.264c0.876,0,1.587-0.711,1.587-1.587C11.587,10.052,11.075,9.433,10.386,9.26z M10,11.586c-0.438,0-0.793-0.354-0.793-0.792c0-0.438,0.355-0.792,0.793-0.792c0.438,0,0.793,0.355,0.793,0.792C10.793,11.232,10.438,11.586,10,11.586z"></path>
						</svg>Date <p id="date"></p>
</a>
            </li>

              <!--<li class="nav-item">
                  <button type="button" onclick="triggerauto()" >Actuator-Auto</button>
              </li>
              <li class="nav-item">
                  <button type="button" onclick="triggermanual()" >Actuator-Manual</button>
              </li>-->

              <li class="nav-item">
                  <!--<a class="nav-link" href="#"><div id="google_translate_element"></div></a>-->
              </li>

          </ul>
        </nav>
      </div>
    </div>

    <script>
                    let trig = 0;
    const triggerauto = () => {
        trig = Math.abs(1-trig);
        fetch(`/weather/motor/`, { method: 'post', body: JSON.stringify({ on: 2 }) }).then(res => res.json()).then(res => console.log(res))
    }
    const triggermanual = () => {
        trig = Math.abs(1-trig);
        fetch(`/weather/motor/`, { method: 'post', body: JSON.stringify({ on: trig }) }).then(res => res.json()).then(res => console.log(res))
    }
    </script>

  {% block body %}
  {% endblock %}
  </body>
</html>

weather/templates/login.html
{% load static %}
<html >
<!--loading css files-->
<head>
  <meta charset="UTF-8">
  <title>Login</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=yes">
  <link rel="stylesheet" href="{% static 'login.css' %}">
</head>
<!--backgorund image-->
<body background="{% static 'plant.jpg'%}">
<!--creating multiple layers for layer over layer effect-->
  <div class="layer0">
  <div class="layer1">
    <div class="login">
       <div class="login__form">
           <!--sends form details for authorization-->
        <form method="POST">
<!--cookies issue-->
    {% csrf_token %}
        <div class="login__row">
<!--allows to draw icons-animation-->
          <svg class="login__icon name svg-icon" viewBox="0 0 20 20">
            <path d="M0,20 a10,8 0 0,1 20,0z M10,0 a4,4 0 0,1 0,8 a4,4 0 0,1 0,-8" />
          </svg>
          <input type="text" class="login__input name" placeholder="Username" name="username" />
        </div>
            <div class="login__row">
            <svg class="login__icon pass svg-icon" viewBox="0 0 20 20">
             <path d="M0,20 20,20 20,8 0,8z M10,13 10,16z M4,8 a6,8 0 0,1 12,0" />
            </svg>
             <input type="password" class="login__input pass" placeholder="Password" name="password"/>
           </div>
        <button type="submit" class="login__submit" >Sign in</button>
</form>
        <p class="login__signup">Don't have an account? &nbsp;<a href="{% url 'weather:register' %}">Sign up</a></p>
      </div>
    </div>
    </div>
  </div>
<!--including javascript jquery lib and other js file-->
      <script src="{% static 'jquery.min.js' %}"></script>
      <script  src="{% static 'login.js' %}"></script>
</body>
</html>